apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: backend.rules
      rules:
        - alert: HighCPUUsage
          expr: rate(process_cpu_user_seconds_total[1m]) > 0.1
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Backend CPU usage is high"