apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: transport-app
type: Opaque
data:
  MONGO_ROOT_USER: YWRtaW4=
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvdHJhbnNwb3J0ZGI=